import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { extractJiraConfigFromSetupFile } from './extract-jira-config.js';

describe('extractJiraConfigFromSetupFile', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'ferry-extract-jira-'));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('extracts owner and repo from dispatch URL', () => {
    const setupContent = `# Ferry — Jira Automation Setup

This file was generated by \`ferry-init\`.

## Prerequisites

- A GitHub fine-grained Personal Access Token (PAT)
  on \`my-org/my-repo\`. Replace \`YOUR_GITHUB_PAT_WITH_REPO_SCOPE\`.

## Rule: Ferry — Refine

**Trigger:** Status changed → To status: \`Refinement\`

**Action:** Send web request

- URL: \`https://api.github.com/repos/my-org/my-repo/dispatches\`
- Method: \`POST\`
`;
    writeFileSync(join(tmpDir, 'ferry-jira-automation-setup.md'), setupContent, 'utf8');

    const result = extractJiraConfigFromSetupFile(tmpDir);
    expect(result).toEqual({ owner: 'my-org', repo: 'my-repo' });
  });

  it('handles repos with hyphens in the name', () => {
    const setupContent = `# Ferry Setup
- URL: \`https://api.github.com/repos/big-emotion/ethniafrica/dispatches\`
`;
    writeFileSync(join(tmpDir, 'ferry-jira-automation-setup.md'), setupContent, 'utf8');

    const result = extractJiraConfigFromSetupFile(tmpDir);
    expect(result).toEqual({ owner: 'big-emotion', repo: 'ethniafrica' });
  });

  it('returns null if file does not exist', () => {
    const result = extractJiraConfigFromSetupFile(tmpDir);
    expect(result).toBeNull();
  });

  it('returns null if dispatch URL is malformed', () => {
    const setupContent = `# Ferry Setup
- URL: \`https://api.github.com/repos/\`
`;
    writeFileSync(join(tmpDir, 'ferry-jira-automation-setup.md'), setupContent, 'utf8');

    const result = extractJiraConfigFromSetupFile(tmpDir);
    expect(result).toBeNull();
  });

  it('handles multiple rules in the file', () => {
    const setupContent = `# Ferry — Jira Automation Setup

### Rule: Ferry — Refine
**Action:** Send web request
- URL: \`https://api.github.com/repos/test-org/test-repo/dispatches\`

### Rule: Ferry — Dev
**Action:** Send web request
- URL: \`https://api.github.com/repos/test-org/test-repo/dispatches\`

### Rule: Ferry — Review
**Action:** Send web request
- URL: \`https://api.github.com/repos/test-org/test-repo/dispatches\`
`;
    writeFileSync(join(tmpDir, 'ferry-jira-automation-setup.md'), setupContent, 'utf8');

    const result = extractJiraConfigFromSetupFile(tmpDir);
    expect(result).toEqual({ owner: 'test-org', repo: 'test-repo' });
  });
});
